// ============================================
// LandingPage.js - Home/Marketing Page
// This is the first page users see when visiting EcoTrip
// It showcases features and encourages sign-ups
// ============================================

// Import Link for navigation between pages
import { Link } from "react-router-dom";

// Import UI components from our component library
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

// Import icons from Lucide React
// Each icon represents a feature or action in our UI
import { 
  Leaf, MapPin, BarChart3, TreePine, Calculator, 
  Sparkles, Globe, ArrowRight, CheckCircle2 
} from "lucide-react";

// Import our custom auth hook to check if user is logged in
import { useAuth } from "@/App";

// Main component function
export default function LandingPage() {
  // Get the current user from auth context
  // This helps us show different CTAs based on login status
  const { user } = useAuth();

  // Array of feature objects - each describes a key feature of EcoTrip
  // Using an array makes it easy to map over and render feature cards
  const features = [
    {
      icon: Sparkles,
      title: "AI-Powered Itineraries",
      description: "Get personalized day-by-day travel plans generated by advanced AI, tailored to your interests and budget.",
      className: "feature-card-1"  // CSS class for grid positioning
    },
    {
      icon: Calculator,
      title: "Carbon Footprint Tracking",
      description: "Real-time CO₂ calculations for transport, accommodation, and activities.",
      className: "feature-card-2"
    },
    {
      icon: TreePine,
      title: "Eco Alternatives",
      description: "Discover greener options like trains instead of flights, eco-lodges, and sustainable activities.",
      className: "feature-card-3"
    },
    {
      icon: BarChart3,
      title: "Analytics Dashboard",
      description: "Visualize your environmental impact with interactive charts and get your personal Green Score.",
      className: "feature-card-4"
    }
  ];

  // Statistics to display - shows the impact of sustainable travel
  const stats = [
    { value: "8%", label: "of global emissions from tourism" },
    { value: "2.5x", label: "lower carbon with eco alternatives" },
    { value: "100+", label: "destinations supported" }
  ];

  return (
    <div className="min-h-screen">
      {/* ============================================
          Hero Section - The main banner at the top
          Features a background image with overlay
          ============================================ */}
      <section className="relative overflow-hidden">
        {/* Background image - absolute positioned to fill container */}
        <div 
          className="absolute inset-0 bg-cover bg-center"
          style={{ 
            backgroundImage: `url('https://images.unsplash.com/photo-1763814809140-1ed738b950af?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDV8MHwxfHNlYXJjaHwyfHxzdXN0YWluYWJsZSUyMHRyYXZlbCUyMG5hdHVyZSUyMGxhbmRzY2FwZXxlbnwwfHx8fDE3Njk2OTM3NTV8MA&ixlib=rb-4.1.0&q=85')` 
          }}
        />
        {/* Gradient overlay to make text readable */}
        <div className="absolute inset-0 hero-overlay" />
        
        {/* Hero content - positioned above the overlay */}
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 md:py-40">
          <div className="max-w-3xl animate-fade-in-up">
            {/* Badge/pill showing what the app does */}
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-white/10 backdrop-blur-md rounded-full text-white/90 text-sm mb-6">
              <Leaf className="w-4 h-4" />
              <span>Sustainable Travel Planning</span>
            </div>
            
            {/* Main headline - uses serif font for elegance */}
            <h1 className="font-serif text-4xl md:text-6xl lg:text-7xl font-bold text-white leading-tight mb-6">
              Travel the World,<br />
              {/* Accent color for emphasis */}
              <span className="text-[#D97C56]">Protect the Planet</span>
            </h1>
            
            {/* Subheadline explaining the value proposition */}
            <p className="text-lg md:text-xl text-white/80 mb-10 max-w-2xl leading-relaxed">
              EcoTrip uses AI to create personalized itineraries while calculating your carbon footprint. 
              Make informed travel choices and discover eco-friendly alternatives.
            </p>
            
            {/* CTA buttons - primary action and secondary link */}
            <div className="flex flex-col sm:flex-row gap-4">
              {/* Primary CTA - links to plan page if logged in, auth if not */}
              <Link to={user ? "/plan" : "/auth"}>
                <Button 
                  size="lg" 
                  className="rounded-full px-8 py-6 text-lg bg-white text-primary hover:bg-white/90 shadow-lg btn-eco"
                  data-testid="hero-cta-btn"
                >
                  Plan Your Eco Trip
                  <ArrowRight className="w-5 h-5 ml-2" />
                </Button>
              </Link>
              {/* Secondary CTA - scrolls to features section */}
              <Link to="#how-it-works">
                <Button 
                  variant="outline" 
                  size="lg"
                  className="rounded-full px-8 py-6 text-lg border-white/30 text-white hover:bg-white/10"
                >
                  Learn More
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* ============================================
          Stats Section - Key statistics about tourism
          ============================================ */}
      <section className="bg-primary py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Grid of 3 stats - responsive columns */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {stats.map((stat, index) => (
              <div key={index} className="text-center">
                {/* Large stat number */}
                <p className="font-serif text-4xl md:text-5xl font-bold text-white mb-2">{stat.value}</p>
                {/* Stat description */}
                <p className="text-primary-foreground/70">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ============================================
          Features Section - Shows app capabilities
          Uses asymmetric grid layout for visual interest
          ============================================ */}
      <section className="py-24 bg-background" id="how-it-works">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Section header */}
          <div className="text-center mb-16">
            <h2 className="font-serif text-3xl md:text-5xl font-bold text-foreground mb-4">
              Smart Travel, Smaller Footprint
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Everything you need to plan sustainable trips that align with your values
            </p>
          </div>

          {/* Feature cards grid - uses custom CSS classes for layout */}
          <div className="feature-grid">
            {features.map((feature, index) => (
              <Card 
                key={index} 
                className={`${feature.className} bg-card border-border/50 shadow-card hover:shadow-soft transition-all duration-300 card-hover overflow-hidden`}
              >
                <CardContent className="p-8">
                  {/* Icon container */}
                  <div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center mb-6">
                    <feature.icon className="w-7 h-7 text-primary" />
                  </div>
                  {/* Feature title */}
                  <h3 className="font-serif text-xl md:text-2xl font-semibold text-foreground mb-3">
                    {feature.title}
                  </h3>
                  {/* Feature description */}
                  <p className="text-muted-foreground leading-relaxed">
                    {feature.description}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* ============================================
          How It Works Section - 3-step process
          ============================================ */}
      <section className="py-24 bg-secondary/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-2 gap-16 items-center">
            {/* Left side - steps */}
            <div>
              <h2 className="font-serif text-3xl md:text-4xl font-bold text-foreground mb-6">
                Three Steps to Sustainable Travel
              </h2>
              
              {/* Steps list with numbered circles */}
              <div className="space-y-8">
                {[
                  { step: "1", title: "Enter Your Trip Details", desc: "Tell us your destination, dates, budget, and interests" },
                  { step: "2", title: "Get AI-Generated Itinerary", desc: "Receive a personalized day-by-day plan with carbon estimates" },
                  { step: "3", title: "Track & Optimize", desc: "View your Green Score and discover eco-friendly alternatives" }
                ].map((item, index) => (
                  <div key={index} className="flex gap-4 animate-fade-in-up" style={{ animationDelay: `${index * 0.15}s` }}>
                    {/* Step number circle */}
                    <div className="flex-shrink-0 w-12 h-12 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold text-lg">
                      {item.step}
                    </div>
                    {/* Step content */}
                    <div>
                      <h3 className="font-semibold text-lg text-foreground mb-1">{item.title}</h3>
                      <p className="text-muted-foreground">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Right side - image with floating card */}
            <div className="relative">
              <img 
                src="https://images.unsplash.com/photo-1669403337335-c25e2d96317d?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1ODh8MHwxfHNlYXJjaHwxfHxoYXBweSUyMHRyYXZlbGVycyUyMGhpa2luZyUyMGJhY2twYWNrfGVufDB8fHx8MTc2OTY5Mzc1OHww&ixlib=rb-4.1.0&q=85"
                alt="Sustainable traveler"
                className="rounded-2xl shadow-soft"
              />
              {/* Floating card overlay - shows Green Score feature */}
              <div className="absolute -bottom-6 -left-6 bg-card p-4 rounded-xl shadow-soft">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center">
                    <CheckCircle2 className="w-6 h-6 text-primary" />
                  </div>
                  <div>
                    <p className="font-semibold text-foreground">Green Score</p>
                    <p className="text-sm text-muted-foreground">Track your impact</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ============================================
          CTA Section - Final call to action
          ============================================ */}
      <section className="py-24 bg-primary">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          {/* Globe icon for visual interest */}
          <Globe className="w-16 h-16 text-primary-foreground/50 mx-auto mb-6" />
          <h2 className="font-serif text-3xl md:text-5xl font-bold text-white mb-6">
            Ready to Travel Responsibly?
          </h2>
          <p className="text-lg text-primary-foreground/80 mb-10 max-w-2xl mx-auto">
            Join thousands of eco-conscious travelers who are making a difference, one trip at a time.
          </p>
          {/* CTA button */}
          <Link to={user ? "/plan" : "/auth"}>
            <Button 
              size="lg"
              className="rounded-full px-10 py-6 text-lg bg-white text-primary hover:bg-white/90 shadow-lg btn-eco"
              data-testid="cta-start-planning-btn"
            >
              Start Planning Free
              <MapPin className="w-5 h-5 ml-2" />
            </Button>
          </Link>
        </div>
      </section>

      {/* ============================================
          Footer - Copyright and branding
          ============================================ */}
      <footer className="py-12 bg-foreground text-primary-foreground/70">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col md:flex-row justify-between items-center gap-6">
            {/* Logo */}
            <div className="flex items-center gap-2">
              <Leaf className="w-6 h-6 text-primary-foreground" />
              <span className="font-serif text-lg font-bold text-primary-foreground">EcoTrip</span>
            </div>
            {/* Copyright text */}
            <p className="text-sm">
              © 2025 EcoTrip. Making sustainable travel accessible.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
